### ISSUE TITLE
源码中type.Bool 类型无法直接使用 true赋值

### ISSUE THREAD

**Issue by byteweap** [smallnest/statsview#1]
如图：
<img width="842" alt="image" src="https://github.com/smallnest/statsview/assets/37861496/c3043d8c-a49a-46e0-9c35-d469ab35d715">
此问题在运行 rpcx官方文档服务端示例时发现，导致rpcx无法正常启动。
解决方式:
type.Bool 使用 opts.Bool(true) 进行赋值

**Comment by byteweap** [comment]
没有深入研究，请问作者大大是否必须通过修改源码进行解决？

**Comment by bububa** [comment]
not compatible with github.com/go-echarts/go-echarts/v2@v2.4.0
need change go-echarts fallback to v2.3.3
and I don't think this package should be bind into the main rpcx, this package is not neccessory at all.

**Comment by byteweap** [comment]
感谢你的回答，不是绑定到rpcx，而是使用rpcx发现的这个问题，然后追踪到这里

**Comment by bububa** [comment]
> 感谢你的回答，不是绑定到rpcx，而是使用rpcx发现的这个问题，然后追踪到这里 

是写给maintainer的，这个库完全没必要集成进rpcx，用opentelemetry就好了

**Comment by byteweap** [comment]
> > 感谢你的回答，不是绑定到rpcx，而是使用rpcx发现的这个问题，然后追踪到这里
> 
> 是写给maintainer的，这个库完全没必要集成进rpcx，用opentelemetry就好了

好的👌
